webhook scaffolding
mengqiy/webhook-scaffolding pull request #1
Opened 2018-09-07 17:43 UTC by mengqiy

This PR shows how the kubebuilder scaffolding based on library in controller-runtime may look like.
Taking one of the webhooks as an example: user only needs to fill in this method https://github.com/mengqiy/webhook-scaffolding/pull/1/files#diff-a6626b678182a0ff6c4aa3119d411fa7R39

2018-09-07 17:44 UTC, mengqiy commented
@droot @DirectXMan12

2018-09-07 23:35 UTC, mengqiy commented
@pwittrock

2018-09-10 14:47 UTC, DirectXMan12 requested changes
some comments on some things that I noticed here that we might want to fix in controller-runtime.

2018-09-10 14:47 UTC, DirectXMan12 commented on cmd/manager/main.go
> +	"log"
should be using logr

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/firstmate/admission/mutating/webhook.go
> +		Type(types.WebhookTypeMutating).
`Type` vs `ForType` seems like it may be confusing in practice, looking at the full example.  Perhaps we should consider renaming `Type` to something else?

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/firstmate/admission/mutating/webhook.go
> +		Type(types.WebhookTypeMutating).
Maybe just have a `.Mutating()` method that marks it as mutating, and assume validating otherwise?

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/firstmate/admission/validating/webhook.go
> +		Path("/validating-firstmates").
how necessary is it to specify this manually?  Can we infer it at all in controller-runtime?

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/pod/admission/mutating/handler.go
> +	anno := pod.GetAnnotations()
why are we using `GetAnnotations` and `SetAnnotations`?  Shouldn't we just be able to do `.Annotations` (I'm assuming this isn't generated, so it's not a big deal, but if we use this as an example, we should clean it up a bit).

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/pod/admission/validating/handler.go
> +}
do we actually need a client here?

2018-09-10 14:47 UTC, DirectXMan12 commented on pkg/webhook/server/server.go
> +		KVMap:   map[string]interface{}{"foo": "bar"},
It's still a bit unclear to me why you'd pass this here as opposed to passing it directly do the struct representing the handler...

2018-09-10 17:05 UTC, mengqiy commented on cmd/manager/main.go
> +	"log"
I agree.
This line is actually generated by kubebuilder.
Filed https://github.com/kubernetes-sigs/kubebuilder/issues/380 last week.

2018-09-10 17:22 UTC, mengqiy commented on pkg/webhook/server/pod/admission/validating/handler.go
> +}
No.
I was thinking if we should always generate `InjectClient` and `InjectDecoder` for the users.
They can delete them if they don't need the client or decoder.

Should we always generate them? WDYT?

2018-09-10 17:39 UTC, mengqiy commented on pkg/webhook/server/pod/admission/mutating/handler.go
> +	anno := pod.GetAnnotations()
No specific reason.
IMO using `GetAnnotations` and `SetAnnotations` be identical of using `.Annotations`. Why you think it's better to use `.Annotations` directly?

2018-09-10 17:55 UTC, DirectXMan12 commented on pkg/webhook/server/pod/admission/mutating/handler.go
> +	anno := pod.GetAnnotations()
it's a bit more in line with the general conventions of core Kube, from what I've seen

2018-09-10 17:55 UTC, DirectXMan12 commented on pkg/webhook/server/pod/admission/validating/handler.go
> +}
I think it's less likely for users to need a client on webhooks, so we can probably not automatically put that in place.

2018-09-10 18:15 UTC, mengqiy commented on pkg/webhook/server/firstmate/admission/validating/webhook.go
> +		Path("/validating-firstmates").
> how necessary is it to specify this manually?

The user doesn't have to specify it manually. Currently we do some simple defaulting for the path.

> Can we infer it at all in controller-runtime?

Yes, I can see 2 ways:
- Theoretically, to make the path strictly unique, we need to put almost everything from the webhook config into the path.
- Use webhook type and resource name in the path, e.g. `mutating_pods`. The generated path is not guaranteed to be unique. For example, mutating pods when CREATE vs mutating pods when UPDATE. If there are 2 `http.Handler` for the same path, [it will panic when registering](https://golang.org/pkg/net/http/#ServeMux.Handle). The user needs to specify the path manually if there is a conflict.

I'm leaning towards the latter one.

2018-09-10 18:25 UTC, mengqiy commented on pkg/webhook/server/pod/admission/validating/handler.go
> +}
> it's less likely for users to need a client on webhooks

I agree. But I do know a use case that people want to build a validating webhook need a client. What they want to do is when validating CRD_foo, they need to check the status of a related CRD_bar.

My concern is that if a user needs a client, how will he/she know that `InjectClient` needs to be implemented to make the client injection happens?
Can we generate `InjectClient` with block comment? So the user can remove the comment if they need a client.

2018-09-10 18:59 UTC, DirectXMan12 commented on pkg/webhook/server/firstmate/admission/validating/webhook.go
> +		Path("/validating-firstmates").
I'm leading towards the latter one as well, and then we can just provide a nice error message for the user if we do a bit of book-keeping ourselves.

2018-09-10 19:00 UTC, DirectXMan12 commented on pkg/webhook/server/pod/admission/validating/handler.go
> +}
We could put it in a block comment.  It's also the same pattern as in the controller reconciler code, which almost always has a client, so there's an easy example already around, most likely.

2018-09-10 20:41 UTC, mengqiy commented on pkg/webhook/server/server.go
> +		KVMap:   map[string]interface{}{"foo": "bar"},
This is because we may have a key-value pair coming from manager's flag. And this key-value pair will be passed to all of the webhook handlers.
GKE have a use case like this.

2018-09-10 20:45 UTC, mengqiy commented
cc: @anfernee

2018-09-11 22:52 UTC, mengqiy commented
@DirectXMan12 Addressed comments. PTAL.

2018-09-19 17:39 UTC, mengqiy commented
@droot Commit `how to support feature gating handlers in scaffolding` shows how we may support disabling handlers.

2018-10-19 23:50 UTC, closed without merging